services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: chesstopia_dev
      POSTGRES_USER: chesstopia
      POSTGRES_PASSWORD: chesstopia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
