spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chesstopia_dev
    username: chesstopia
    password: chesstopia
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true

logging:
  level:
    io.chesstopia: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
