spring:
  application:
    name: chesstopia-backend
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
